# Generated by Django 4.1.3 on 2023-02-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInkForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=50)),
                ('surnam', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('messag', models.TextField()),
                ('passwor', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
