# Generated by Django 4.1.3 on 2023-02-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portail_Etudiant', '0002_cours_uuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='titre',
        ),
        migrations.AddField(
            model_name='cours',
            name='description',
            field=models.CharField(default='nothing', max_length=200),
        ),
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(default='course/pexels-antonio-batinić-4164418.jpg', upload_to='course'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='category',
            field=models.CharField(choices=[('AL', 'ALGORITHMIQUE'), ('MA', 'MATHS'), ('RE', 'RESEAU'), ('DP', 'DEVELOPPEMENT PERSONNEL')], max_length=20),
        ),
    ]
