# Generated by Django 4.1.3 on 2023-02-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portail_Etudiant', '0003_remove_cours_titre_cours_description_cours_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='category',
            field=models.CharField(choices=[('ALGORITHMIQUE', 'AL'), ('MATHS', 'MA'), ('RESEAU', 'RE'), ('DEVELOPPEMENT PERSONNEL', 'DP')], max_length=40),
        ),
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(default='pexels-karolina-grabowska-6256241_dRPoLSw.jpg', upload_to='course'),
        ),
    ]
