# Generated by Django 4.1.3 on 2023-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portail_Etudiant', '0005_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='category',
            field=models.CharField(choices=[('ALGORITHMIcs', 'AL'), ('MATHS', 'MA'), ('NETWORK', 'RE'), ('PERSONNAL DEVELOPPEMENT', 'DP')], max_length=40),
        ),
    ]
